name: Sync Image to Aliyun  Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: 
        password: 
        logout: false

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy docker://docker.io/library/nginx:stable-alpine docker://registry.cn-hangzhou.aliyuncs.com/zjm-test/nginx:stable-alpine
         skopeo copy docker://docker.io/library/mysql:5.7 docker://registry.cn-hangzhou.aliyuncs.com/zjm-test/mysql:5.7
         skopeo copy docker://docker.io/library/redis:6.2 docker://registry.cn-hangzhou.aliyuncs.com/zjm-test/redis:6.2
         skopeo copy docker://docker.io/prom/prometheus:latest docker://registry.cn-hangzhou.aliyuncs.com/zjm-test/prometheus:latest
         skopeo copy docker://flashcatcloud/categraf:latest docker://registry.cn-hangzhou.aliyuncs.com/zjm-test/categraf:latest
         skopeo copy docker://flashcatcloud/nightingale:6.3.4 docker://registry.cn-hangzhou.aliyuncs.com/zjm-test/nightingale:6.3.4
