name: Sync Image to Aliyun  Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: 17681863060
        password: Zjm@12345
        logout: false

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy docker://docker.io/jumpserver/jms_core:v4.0.1 docker://registry.cn-hangzhou.aliyuncs.com/zjm-test/jms_core:v4.0.1
         skopeo copy docker://docker.io/jumpserver/jms_koko:v4.0.1 docker://registry.cn-hangzhou.aliyuncs.com/zjm-test/jms_koko:v4.0.1
         skopeo copy docker://docker.io/jumpserver/guacd:1.5.5-bookworm docker://registry.cn-hangzhou.aliyuncs.com/zjm-test/guacd:1.5.5-bookworm
         skopeo copy docker://docker.io/jumpserver/jms_lion:v4.0.1 docker://registry.cn-hangzhou.aliyuncs.com/zjm-test/jms_lion:v4.0.1
         skopeo copy docker://docker.io/jumpserver/jms_chen:v4.0.1 docker://registry.cn-hangzhou.aliyuncs.com/zjm-test/jms_chen:v4.0.1
         skopeo copy docker://docker.io/jumpserver/jms_web:v4.0.1 docker://registry.cn-hangzhou.aliyuncs.com/zjm-test/jms_web:v4.0.1
